#!/usr/bin/env python3

import argparse
import subprocess
import sys

if __name__ == '__main__':
    # Parse arguments
    parser = argparse.ArgumentParser("extism-lldb", description="LLDB for Extism plugins")
    parser.add_argument("plugin_file", help="WASM or Manifest file")
    parser.add_argument("function_name", help="Plugin function")
    parser.add_argument("--input", "-i", help="Input data. '@' prefix can be used to load input directly from a file", default="")
    parser.add_argument("--lldb", metavar="EXECUTABLE", help="LLDB executable", default="lldb")
    parser.add_argument("lldb_arguments", nargs='*', help="LLDB arguments")
    args = parser.parse_args()

    # Build argument list
    proc_args = [args.lldb]
    proc_args.extend(args.lldb_arguments)
    proc_args.append("--one-line")
    proc_args.append(f"b {args.function_name}")
    proc_args.append("--")
    proc_args.append("./extism-dbg")
    proc_args.append(args.plugin_file)
    proc_args.append(args.function_name)
    proc_args.append(args.input)

    # Run LLDD
    sys.exit(subprocess.Popen(proc_args,).wait())
