name: Check

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/libextism

    - name: make
      run: make

    - name: make check
      run: LD_LIBRARY_PATH=/usr/local/lib make check
